### get administradores
GET http://localhost:8080/administradores
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2RfYWRtaW5pc3RyYWRvciI6Niwibm9tYnJlIjoiSnVhbiIsImFwZWxsaWRvIjoiR2FyY2lhIiwiZG5pIjozNDM0NCwiZmVjaGFfaW5pX2NvbnRyYXRvIjoiMjAyNC0wOS0wOVQwMDowMDowMC4wMDBaIiwiZmVjaGFfZmluX2NvbnRyYXRvIjpudWxsLCJjb250cmFzZW5pYSI6IiQyYSQxMCRJRlFhaXJxNjhKUWdhN1VJemRiMmh1THNhWkxqV1NsN0p6OFdEbmV3eTJXVFpZd29uZERPdSIsImlhdCI6MTczOTgxMjcwOSwiZXhwIjoxNzM5ODIzNTA5fQ.BZRby-NFtW3h0Ttjd1keFzBDYOt_Gox2pBQr8q91ZV4"

### get administrador
GET http://localhost:8080/administradores/1
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2RfYWRtaW5pc3RyYWRvciI6Niwibm9tYnJlIjoiSnVhbiIsImFwZWxsaWRvIjoiR2FyY2lhIiwiZG5pIjozNDM0NCwiZmVjaGFfaW5pX2NvbnRyYXRvIjoiMjAyNC0wOS0wOVQwMDowMDowMC4wMDBaIiwiZmVjaGFfZmluX2NvbnRyYXRvIjpudWxsLCJjb250cmFzZW5pYSI6IiQyYSQxMCRJRlFhaXJxNjhKUWdhN1VJemRiMmh1THNhWkxqV1NsN0p6OFdEbmV3eTJXVFpZd29uZERPdSIsImlhdCI6MTczOTgxMjcwOSwiZXhwIjoxNzM5ODIzNTA5fQ.BZRby-NFtW3h0Ttjd1keFzBDYOt_Gox2pBQr8q91ZV4"

### log in de administrador
POST http://localhost:8080/administradores/logIn
Content-Type: application/json

{
    "cod_administrador": 6,
    "contrasenia": "123r"
}

### POST an admin
POST http://localhost:8080/administradores/
Content-Type: application/json

{
    "nombre": "Juan",
    "apellido": "Lopez",
    "dni": 343445,
    "fecha_ini_contrato": "2024-09-09",
    "fecha_fin_contrato": null,
    "contrasenia": "123r",
    "es_especial": false
}





