### get administradores
GET http://localhost:8080/administradores
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2RfYWRtaW5pc3RyYWRvciI6Nywibm9tYnJlIjoiSnVhbiIsImFwZWxsaWRvIjoiTG9wZXoiLCJkbmkiOjM0MzQ0NSwiZmVjaGFfaW5pX2NvbnRyYXRvIjoiMjAyNC0wOS0wOVQwMDowMDowMC4wMDBaIiwiZmVjaGFfZmluX2NvbnRyYXRvIjpudWxsLCJjb250cmFzZW5pYSI6IiQyYSQxMCRqVmkwaFlldEtqSzNsNjlLLkFTczcuTlc3TUgxL2RKOEQ5cVhuQlZRdFNEVm5FRTFGYTlwNiIsInBlcm1pc3Npb25zIjpbIiEqIl0sImlhdCI6MTc0MDU4NTU2OCwiZXhwIjoxNzQwNTk2MzY4fQ.JRg90XPmQ2nvGw5lGMDRulpa3vwrp2OzP77oyeF4YLU"

### get administrador
GET http://localhost:8080/administradores/1
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2RfYWRtaW5pc3RyYWRvciI6Nywibm9tYnJlIjoiSnVhbiIsImFwZWxsaWRvIjoiTG9wZXoiLCJkbmkiOjM0MzQ0NSwiZmVjaGFfaW5pX2NvbnRyYXRvIjoiMjAyNC0wOS0wOVQwMDowMDowMC4wMDBaIiwiZmVjaGFfZmluX2NvbnRyYXRvIjpudWxsLCJjb250cmFzZW5pYSI6IiQyYSQxMCRqVmkwaFlldEtqSzNsNjlLLkFTczcuTlc3TUgxL2RKOEQ5cVhuQlZRdFNEVm5FRTFGYTlwNiIsInBlcm1pc3Npb25zIjpbIiEqIl0sImlhdCI6MTc0MDU4NTU2OCwiZXhwIjoxNzQwNTk2MzY4fQ.JRg90XPmQ2nvGw5lGMDRulpa3vwrp2OzP77oyeF4YLU"

### log in de administrador
POST http://localhost:8080/administradores/logIn
Content-Type: application/json

{
    "cod_administrador": 7,
    "contrasenia": "123r"
}

### POST an admin
POST http://localhost:8080/administradores/
Content-Type: application/json

{
    "nombre": "Juan",
    "apellido": "Lopez",
    "dni": 343445,
    "fecha_ini_contrato": "2024-09-09",
    "fecha_fin_contrato": null,
    "contrasenia": "123r",
    "es_especial": false
}





