### get all
GET http://localhost:8080/celdas
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2RfYWRtaW5pc3RyYWRvciI6MTAsIm5vbWJyZSI6Ikp1YW4iLCJhcGVsbGlkbyI6IkdhcmNpYSIsImRuaSI6MzQzNDM0MzAsImZlY2hhX2luaV9jb250cmF0byI6IjIwMjQtMDktMDlUMDA6MDA6MDAuMDAwWiIsImZlY2hhX2Zpbl9jb250cmF0byI6bnVsbCwiY29udHJhc2VuaWEiOiIkMmEkMTAkVDAzdXI4eWVxVWFNSndoWlJITnVhdWNleUxuSVFXUi5OSzM5Y2NNOXpwUmx5MlJDN091VGEiLCJpYXQiOjE3MzgyOTM3MDEsImV4cCI6MTczODMwNDUwMX0.Q5KzscefR4O3uOOr5EKFsCJvbnNQi8Yso0UJXtProIo"


### get one
GET http://localhost:8080/celdas/1
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2RfYWRtaW5pc3RyYWRvciI6MTAsIm5vbWJyZSI6Ikp1YW4iLCJhcGVsbGlkbyI6IkdhcmNpYSIsImRuaSI6MzQzNDM0MzAsImZlY2hhX2luaV9jb250cmF0byI6IjIwMjQtMDktMDlUMDA6MDA6MDAuMDAwWiIsImZlY2hhX2Zpbl9jb250cmF0byI6bnVsbCwiY29udHJhc2VuaWEiOiIkMmEkMTAkVDAzdXI4eWVxVWFNSndoWlJITnVhdWNleUxuSVFXUi5OSzM5Y2NNOXpwUmx5MlJDN091VGEiLCJpYXQiOjE3MzgyOTM3MDEsImV4cCI6MTczODMwNDUwMX0.Q5KzscefR4O3uOOr5EKFsCJvbnNQi8Yso0UJXtProIo"


