### get talleres
GET http://localhost:8080/talleres

### get actividad
GET http://localhost:8080/talleres/1

### POST an actividad
POST http://localhost:8080/talleres
Content-Type: application/json

{
    "nombre": "recolectamos naranjas",
    "descripcion": "recolectamos naranjas", 
    "locacion": "arboleda del sector 1", 
    "dia_de_la_semana": 3, 
    "hora_inicio": 23, 
    "hora_fin": 24
}

### inscripcion :cod_taller&:cod_recluso
POST http://localhost:8080/talleres/inscripcion/1&13

### modificar taller
PUT http://localhost:8080/talleres/2
Content-Type: application/json

{
    "nombre": "recoleccion de kiwis radioactivos",
    "descripcion": "recolectamos kiwis radioactivos", 
    "locacion": "arboleda del sector 1", 
    "estado": false
}

