### get talleres
GET http://localhost:8080/talleres

### get actividad
GET http://localhost:8080/talleres/5

### POST an actividad
POST http://localhost:8080/talleres
Content-Type: application/json

{
    "nombre": "re",
    "descripcion": "recolectamos naranjas", 
    "locacion": "arboleda del sector 1", 
    "diaDeLaSemana": 4, 
    "horaInicio": 23, 
    "horaFin": 24,
    "estado": 1
}

### inscripcion :cod_taller&:cod_recluso
POST http://localhost:8080/talleres/inscripcion/1&12

### modificar taller
PUT http://localhost:8080/talleres/5
Content-Type: application/json

{
    "nombre": "recoleccion de kiwis radioactivos",
    "descripcion": "recolectamos kiwis radioactivos", 
    "locacion": "arboleda del sector 1", 
    "diaDeLaSemana": 4, 
    "horaInicio": 23, 
    "horaFin": 24,
    "estado": 0
}

