### get actividades ilegales
GET http://localhost:8080/actividades_ilegales
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2RfYWRtaW5pc3RyYWRvciI6MTAsIm5vbWJyZSI6Ikp1YW4iLCJhcGVsbGlkbyI6IkdhcmNpYSIsImRuaSI6MzQzNDM0MzAsImZlY2hhX2luaV9jb250cmF0byI6IjIwMjQtMDktMDlUMDA6MDA6MDAuMDAwWiIsImZlY2hhX2Zpbl9jb250cmF0byI6bnVsbCwiY29udHJhc2VuaWEiOiIkMmEkMTAkVDAzdXI4eWVxVWFNSndoWlJITnVhdWNleUxuSVFXUi5OSzM5Y2NNOXpwUmx5MlJDN091VGEiLCJpYXQiOjE3MzgzNDgzMTEsImV4cCI6MTczODM1OTExMX0._7KsyuxdYpfbxz4M3PZXIYzZuJfIBNgtrwcg-2Q9V8Q"

### get reclusos
GET http://localhost:8080/actividades_ilegales/2
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2RfYWRtaW5pc3RyYWRvciI6OSwibm9tYnJlIjoiSnVhbiIsImFwZWxsaWRvIjoiTG9wZXoiLCJkbmkiOjM0MzQ0NTgzLCJjb250cmFzZW5pYSI6IiQyYSQxMCRrUG9FMFd6dW0vNnlrVFRLLkNLSVAudTNBQlN0aGFMWmIyMS8waGcwRndRQ2Z1WVZFNUxrYSIsImVzX2VzcGVjaWFsIjp0cnVlLCJpYXQiOjE3NDI2MTU5MzYsImV4cCI6MTc0MjYyNjczNn0.woVrZbkAX0Ih01MRjpi0fD5Dh7-o3qfv4-P7-E29vSk"

### POST an actividad
POST http://localhost:8080/actividades_ilegales
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2RfYWRtaW5pc3RyYWRvciI6MTAsIm5vbWJyZSI6Ikp1YW4iLCJhcGVsbGlkbyI6IkdhcmNpYSIsImRuaSI6MzQzNDM0MzAsImZlY2hhX2luaV9jb250cmF0byI6IjIwMjQtMDktMDlUMDA6MDA6MDAuMDAwWiIsImZlY2hhX2Zpbl9jb250cmF0byI6bnVsbCwiY29udHJhc2VuaWEiOiIkMmEkMTAkVDAzdXI4eWVxVWFNSndoWlJITnVhdWNleUxuSVFXUi5OSzM5Y2NNOXpwUmx5MlJDN091VGEiLCJpYXQiOjE3MzgzNDgzMTEsImV4cCI6MTczODM1OTExMX0._7KsyuxdYpfbxz4M3PZXIYzZuJfIBNgtrwcg-2Q9V8Q"
Content-Type: application/json

{
    "nombre": "recoleccion de manzanas",
    "descripcion": "recolectamos manzanas", 
    "locacion": "arboleda del sector 1", 
    "dia_de_la_semana": 3, 
    "hora_inicio": 23, 
    "hora_fin": 24,
    "cantidad_maxima": 10
}

### modificar an actividad
PUT http://localhost:8080/actividades_ilegales/2
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2RfYWRtaW5pc3RyYWRvciI6MTAsIm5vbWJyZSI6Ikp1YW4iLCJhcGVsbGlkbyI6IkdhcmNpYSIsImRuaSI6MzQzNDM0MzAsImZlY2hhX2luaV9jb250cmF0byI6IjIwMjQtMDktMDlUMDA6MDA6MDAuMDAwWiIsImZlY2hhX2Zpbl9jb250cmF0byI6bnVsbCwiY29udHJhc2VuaWEiOiIkMmEkMTAkVDAzdXI4eWVxVWFNSndoWlJITnVhdWNleUxuSVFXUi5OSzM5Y2NNOXpwUmx5MlJDN091VGEiLCJpYXQiOjE3MzgzNDg1NjUsImV4cCI6MTczODM1OTM2NX0.bMk_ryljszsKqVeupPSfPYd00raI7pOtgr9gLpO0KNA"
Content-Type: application/json

{
    "nombre": "recoleccion de naranjas radioactiva",
    "descripcion": "recolectamos naranjas radioactivas", 
    "estado": false
}


### inscribir a act ilegal :cod_act_ilegal&:cod_recluso
POST http://localhost:8080/actividades_ilegales/inscripcion/1&11
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2RfYWRtaW5pc3RyYWRvciI6MTAsIm5vbWJyZSI6Ikp1YW4iLCJhcGVsbGlkbyI6IkdhcmNpYSIsImRuaSI6MzQzNDM0MzAsImZlY2hhX2luaV9jb250cmF0byI6IjIwMjQtMDktMDlUMDA6MDA6MDAuMDAwWiIsImZlY2hhX2Zpbl9jb250cmF0byI6bnVsbCwiY29udHJhc2VuaWEiOiIkMmEkMTAkVDAzdXI4eWVxVWFNSndoWlJITnVhdWNleUxuSVFXUi5OSzM5Y2NNOXpwUmx5MlJDN091VGEiLCJpYXQiOjE3MzgzNDgzMTEsImV4cCI6MTczODM1OTExMX0._7KsyuxdYpfbxz4M3PZXIYzZuJfIBNgtrwcg-2Q9V8Q"



