### get all
GET http://localhost:8080/condenas
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2RfYWRtaW5pc3RyYWRvciI6MSwibm9tYnJlIjoiSnVhbiIsImFwZWxsaWRvIjoiTG9wZXoiLCJkbmkiOjM0MzQ0NTgzLCJjb250cmFzZW5pYSI6IiQyYSQxMCRybG1BaWV0bkJTdFRpck9SWHdHYk1lL2JqYmcxMFA0TkRMbGs2WE5JZjFIVEtGcUlicjBzSyIsImVzX2VzcGVjaWFsIjp0cnVlLCJpYXQiOjE3NTM3NTQ5OTgsImV4cCI6MTc1Mzc2NTc5OH0.3NuYTwUyVSe0Hbpzi3dngVYAvKwN3E97Vkz5DjthZXw"

### agregar sentencias a sector, es importante que los campos tengan nombres diferentes
POST http://localhost:8080/condenas
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2RfYWRtaW5pc3RyYWRvciI6MSwibm9tYnJlIjoiSnVhbiIsImFwZWxsaWRvIjoiTG9wZXoiLCJkbmkiOjM0MzQ0NTgzLCJjb250cmFzZW5pYSI6IiQyYSQxMCRybG1BaWV0bkJTdFRpck9SWHdHYk1lL2JqYmcxMFA0TkRMbGs2WE5JZjFIVEtGcUlicjBzSyIsImVzX2VzcGVjaWFsIjp0cnVlLCJpYXQiOjE3NTM4MDExNzEsImV4cCI6MTc1MzgxMTk3MX0.MBbW3HOq2k5DPiJhHfJ39tSA54aUxpMgeLLFqEj9Cvc"
Content-Type: application/json

{
    "cod_recluso": 26,
    "cod_sentencias": [4]
}

### finalizar condenas
PATCH http://localhost:8080/condenas/finalizar_condenas
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2RfYWRtaW5pc3RyYWRvciI6MSwibm9tYnJlIjoiSnVhbiIsImFwZWxsaWRvIjoiTG9wZXoiLCJkbmkiOjM0MzQ0NTgzLCJjb250cmFzZW5pYSI6IiQyYSQxMCRybG1BaWV0bkJTdFRpck9SWHdHYk1lL2JqYmcxMFA0TkRMbGs2WE5JZjFIVEtGcUlicjBzSyIsImVzX2VzcGVjaWFsIjp0cnVlLCJpYXQiOjE3NTM4MDExNzEsImV4cCI6MTc1MzgxMTk3MX0.MBbW3HOq2k5DPiJhHfJ39tSA54aUxpMgeLLFqEj9Cvc"





