### get all
GET http://localhost:8080/condenas
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2RfYWRtaW5pc3RyYWRvciI6Niwibm9tYnJlIjoiSnVhbiIsImFwZWxsaWRvIjoiTG9wZXoiLCJkbmkiOjM0MzQ0NTMsImZlY2hhX2luaV9jb250cmF0byI6IjIwMjQtMDktMDlUMDA6MDA6MDAuMDAwWiIsImZlY2hhX2Zpbl9jb250cmF0byI6bnVsbCwiY29udHJhc2VuaWEiOiIkMmEkMTAkLi9xQ1ZrN3VMVm84UU1hbHUuLlYyTzAzQWFCYk5lZGROa0ZhdnRYNGZqV1BYQThkY3NEak8iLCJlc19lc3BlY2lhbCI6dHJ1ZSwiaWF0IjoxNzQxODM4ODUwLCJleHAiOjE3NDE4NDk2NTB9.MnwMuOa636Lutqxb64zUs3McMY9-K0HWbbziJt8-QbI"

### agregar sentencias a sector, es importante que los campos tengan nombres diferentes
POST http://localhost:8080/condenas
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2RfYWRtaW5pc3RyYWRvciI6MSwibm9tYnJlIjoiSnVhbiIsImFwZWxsaWRvIjoiTG9wZXoiLCJkbmkiOjM0MzQ0NTMsImZlY2hhX2luaV9jb250cmF0byI6IjIwMjQtMDktMDlUMDA6MDA6MDAuMDAwWiIsImZlY2hhX2Zpbl9jb250cmF0byI6bnVsbCwiY29udHJhc2VuaWEiOiIkMmEkMTAkeG5lakJSTFo3QTJGSUV0aVlidm53ZVVxbTZWVk52Y0pwV2RoNlB2dG5MQm5lWFJ1bTk0d3kiLCJlc19lc3BlY2lhbCI6dHJ1ZSwiaWF0IjoxNzQyMjM5MzcyLCJleHAiOjE3NDIyNTAxNzJ9.zTKlptGWOINIge1Y-kfJwBMBq3PXJxYs-Vt4a_8_9qw"
Content-Type: application/json

{
    "cod_recluso": 29,
    "cod_sentencias": [4, 3]
}

### finalizar condenas
POST http://localhost:8080/condenas/finalizar_condenas
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2RfYWRtaW5pc3RyYWRvciI6MSwibm9tYnJlIjoiSnVhbiIsImFwZWxsaWRvIjoiTG9wZXoiLCJkbmkiOjM0MzQ0NTMsImZlY2hhX2luaV9jb250cmF0byI6IjIwMjQtMDktMDlUMDA6MDA6MDAuMDAwWiIsImZlY2hhX2Zpbl9jb250cmF0byI6bnVsbCwiY29udHJhc2VuaWEiOiIkMmEkMTAkeG5lakJSTFo3QTJGSUV0aVlidm53ZVVxbTZWVk52Y0pwV2RoNlB2dG5MQm5lWFJ1bTk0d3kiLCJlc19lc3BlY2lhbCI6dHJ1ZSwiaWF0IjoxNzQyMjM5MzcyLCJleHAiOjE3NDIyNTAxNzJ9.zTKlptGWOINIge1Y-kfJwBMBq3PXJxYs-Vt4a_8_9qw"



