### get all
GET http://localhost:8080/condenas

### agregar sentencias a sector, es importante que los campos tengan nombres diferentes
POST http://localhost:8080/condenas
Content-Type: application/json

{
    "cod_recluso": 13,
    "cod_sentencias": [1,4,5]
}

### finalizar condenas
PUT http://localhost:8080/condenas/finalizarCondenas

