### get all guardias
GET http://localhost:8080/guardias
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2RfYWRtaW5pc3RyYWRvciI6MSwibm9tYnJlIjoiSnVhbiIsImFwZWxsaWRvIjoiTG9wZXoiLCJkbmkiOjM0MzQ0NTgzLCJjb250cmFzZW5pYSI6IiQyYSQxMCRybG1BaWV0bkJTdFRpck9SWHdHYk1lL2JqYmcxMFA0TkRMbGs2WE5JZjFIVEtGcUlicjBzSyIsImVzX2VzcGVjaWFsIjp0cnVlLCJpYXQiOjE3NTQzMjIxNTYsImV4cCI6MTc1NDMzMjk1Nn0.gz6Ek5GwV7VlES2Gq54YeI33J0Un8-ap7hz93mto57M"

### get guardia
GET http://localhost:8080/guardias/43434343
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2RfYWRtaW5pc3RyYWRvciI6MTAsIm5vbWJyZSI6Ikp1YW4iLCJhcGVsbGlkbyI6IkdhcmNpYSIsImRuaSI6MzQzNDM0MzAsImZlY2hhX2luaV9jb250cmF0byI6IjIwMjQtMDktMDlUMDA6MDA6MDAuMDAwWiIsImZlY2hhX2Zpbl9jb250cmF0byI6bnVsbCwiY29udHJhc2VuaWEiOiIkMmEkMTAkVDAzdXI4eWVxVWFNSndoWlJITnVhdWNleUxuSVFXUi5OSzM5Y2NNOXpwUmx5MlJDN091VGEiLCJpYXQiOjE3MzgyOTM3MDEsImV4cCI6MTczODMwNDUwMX0.Q5KzscefR4O3uOOr5EKFsCJvbnNQi8Yso0UJXtProIo"


### post guardia
POST http://localhost:8080/guardias 
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2RfYWRtaW5pc3RyYWRvciI6MSwibm9tYnJlIjoiSnVhbiIsImFwZWxsaWRvIjoiTG9wZXoiLCJkbmkiOjM0MzQ0NTgzLCJjb250cmFzZW5pYSI6IiQyYSQxMCRybG1BaWV0bkJTdFRpck9SWHdHYk1lL2JqYmcxMFA0TkRMbGs2WE5JZjFIVEtGcUlicjBzSyIsImVzX2VzcGVjaWFsIjp0cnVlLCJpYXQiOjE3NTQzMjIxNTYsImV4cCI6MTc1NDMzMjk1Nn0.gz6Ek5GwV7VlES2Gq54YeI33J0Un8-ap7hz93mto57M"
Content-Type: application/json

{
    "nombre": "Ignacio",
    "apellido": "Chaparro",
    "dni": 43434343
}

### finalizar contrato
PUT http://localhost:8080/guardias/finalizarContrato
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2RfYWRtaW5pc3RyYWRvciI6MSwibm9tYnJlIjoiSnVhbiIsImFwZWxsaWRvIjoiTG9wZXoiLCJkbmkiOjM0MzQ0NTgzLCJjb250cmFzZW5pYSI6IiQyYSQxMCRybG1BaWV0bkJTdFRpck9SWHdHYk1lL2JqYmcxMFA0TkRMbGs2WE5JZjFIVEtGcUlicjBzSyIsImVzX2VzcGVjaWFsIjp0cnVlLCJpYXQiOjE3NTQzMjI1OTYsImV4cCI6MTc1NDMzMzM5Nn0.gB_dH20FTi-1YuDVfTmmFB-eRHw03FhqyQxDjyFcODY"
Content-Type: application/json

{
    "cod_guardia": 8
}






