### get all sentencias
GET http://localhost:8080/sentencias
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2RfYWRtaW5pc3RyYWRvciI6MSwibm9tYnJlIjoiSnVhbiIsImFwZWxsaWRvIjoiTG9wZXoiLCJkbmkiOjM0MzQ0NTMsImZlY2hhX2luaV9jb250cmF0byI6IjIwMjQtMDktMDlUMDA6MDA6MDAuMDAwWiIsImZlY2hhX2Zpbl9jb250cmF0byI6bnVsbCwiY29udHJhc2VuaWEiOiIkMmEkMTAkQmZDM3duTHlDMnllcVJPU2lyWVlDZU9tQTZhMExMR3VUN0VCYXkzdTJ5U1FHSFdBZ1hwckMiLCJlc19lc3BlY2lhbCI6dHJ1ZSwiaWF0IjoxNzQxOTg0MDc3LCJleHAiOjE3NDE5OTQ4Nzd9.xVElXdAt9YhV-71HXzhm8GVuxNAlMlya3F_695MIMtA"

### get a sentencia
GET http://localhost:8080/sentencias/5
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2RfYWRtaW5pc3RyYWRvciI6MSwibm9tYnJlIjoiSnVhbiIsImFwZWxsaWRvIjoiTG9wZXoiLCJkbmkiOjM0MzQ0NTMsImZlY2hhX2luaV9jb250cmF0byI6IjIwMjQtMDktMDlUMDA6MDA6MDAuMDAwWiIsImZlY2hhX2Zpbl9jb250cmF0byI6bnVsbCwiY29udHJhc2VuaWEiOiIkMmEkMTAkQmZDM3duTHlDMnllcVJPU2lyWVlDZU9tQTZhMExMR3VUN0VCYXkzdTJ5U1FHSFdBZ1hwckMiLCJlc19lc3BlY2lhbCI6dHJ1ZSwiaWF0IjoxNzQxOTg0MDc3LCJleHAiOjE3NDE5OTQ4Nzd9.xVElXdAt9YhV-71HXzhm8GVuxNAlMlya3F_695MIMtA"

### post una sentencia
POST http://localhost:8080/sentencias
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2RfYWRtaW5pc3RyYWRvciI6MSwibm9tYnJlIjoiSnVhbiIsImFwZWxsaWRvIjoiTG9wZXoiLCJkbmkiOjM0MzQ0NTMsImZlY2hhX2luaV9jb250cmF0byI6IjIwMjQtMDktMDlUMDA6MDA6MDAuMDAwWiIsImZlY2hhX2Zpbl9jb250cmF0byI6bnVsbCwiY29udHJhc2VuaWEiOiIkMmEkMTAkQmZDM3duTHlDMnllcVJPU2lyWVlDZU9tQTZhMExMR3VUN0VCYXkzdTJ5U1FHSFdBZ1hwckMiLCJlc19lc3BlY2lhbCI6dHJ1ZSwiaWF0IjoxNzQxOTg0MDc3LCJleHAiOjE3NDE5OTQ4Nzd9.xVElXdAt9YhV-71HXzhm8GVuxNAlMlya3F_695MIMtA"
Content-Type: application/json

{
    "nombre": "pensar que mexico tiene mejoutbol que otros pa",
    "descripcion": "inclusive groelandia tiene mejor futbol que ustedes mexas bobos", 
    "duracion_anios": 76,
    "orden_de_gravedad": 59
}



