### get actividades
GET http://localhost:8080/actividades
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2RfYWRtaW5pc3RyYWRvciI6MSwibm9tYnJlIjoiSnVhbiBFc3RldmFuIiwiYXBlbGxpZG8iOiJHYXJjaWEiLCJkbmkiOjM0MzQzNDM5LCJmZWNoYV9pbmlfY29udHJhdG8iOiIyMDI0LTA5LTA5VDAwOjAwOjAwLjAwMFoiLCJmZWNoYV9maW5fY29udHJhdG8iOiIyMDI0LTA5LTA5VDAwOjAwOjAwLjAwMFoiLCJjb250cmFzZW5pYSI6IiQyYSQxMCRrQ3hLS2I5MWFGVW8yUWhQRWgvL01lbDlXWVFhTG1YVUpnVGhHeDRLMzFPaFhJVmMwbnl0VyIsImlhdCI6MTczODAxMzU1MywiZXhwIjoxNzM4MDI0MzUzfQ.Fpvb10Ytjsfhn_iCTjNLqnGhJrjWSZzunkncHS-Pb1c"

### get actividad
GET http://localhost:8080/actividades/1

### POST an actividad
POST http://localhost:8080/actividades
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2RfYWRtaW5pc3RyYWRvciI6MSwibm9tYnJlIjoiSnVhbiIsImFwZWxsaWRvIjoiTG9wZXoiLCJkbmkiOjM0MzQ0NTgzLCJjb250cmFzZW5pYSI6IiQyYSQxMCRybG1BaWV0bkJTdFRpck9SWHdHYk1lL2JqYmcxMFA0TkRMbGs2WE5JZjFIVEtGcUlicjBzSyIsImVzX2VzcGVjaWFsIjp0cnVlLCJpYXQiOjE3NTQ4NjIyODgsImV4cCI6MTc1NDg3MzA4OH0.cJPqKxnW9E6OXZ9qprQroAdSP8Kb6bawktWyR5aortA"
Content-Type: application/json

{
    "nombre": "recoleccion de naranjas",
    "descripcion": "recolectamos naranjas", 
    "locacion": "arboleda del sector 1", 
    "dia_de_la_semana": 4, 
    "hora_inicio": 23, 
    "hora_fin": 24,
    "cantidad_minima": 4,
    "edad_minima": 20, 
    "cod_sector": 4
}

### modificar an actividad
PUT http://localhost:8080/actividades/1
Content-Type: application/json

{
    "nombre": "recoleccion de naranjas radioactiva",
    "descripcion": "recolectamos naranjas radioactivas", 
    "locacion": "chernobyl sector 1", 
    "estado": false
}



