//
// use heroclash4geeks

//insert data

  
db.guardias.insertOne({
    name: 'bodoque',
    apellido: 'wuebon'
})
  
  // query
db.guardias.find()
db.characters.find({ characterClass: 'Jedi' })
db.characters.find({ mana: { $gt: 30 } })
db.characters.find({ mana: { $gt: 30 } }, { name: 1, characterClass: 1 })
db.characters.find({ mana: { $gt: 30 } }, { name: 1, characterClass: 1, _id: 0 })
db.characters.find({ _id: ObjectId('65155fb42f53abe42bd53cee') }) //change the id according to the autogenerated value
  
  //update
db.characters.updateOne({ name: 'Darth Vader' }, { $set: { name: 'Anakin Skywalker', characterClass: 'Fallen Jedi' } })
  
  //delete
db.characters.deleteOne({ characterClass: 'Jedi' })
