### get all
GET http://localhost:8080/sectores

### get one
GET http://localhost:8080/sectores/1

### get celdas
GET http://localhost:8080/sectores/celdas/1

### agregar sentencias a sector, es importante que los campos tengan nombres diferentes
POST http://localhost:8080/sectores/agregarSentenciasEn1
Content-Type: application/json

{
    "cod_sentencia1": 10,
    "cod_sentencia2": 8,
    "cod_sentencia3": 9
}





### get actividades
GET http://localhost:8080/actividades

### get actividad
GET http://localhost:8080/actividades/3

### POST an actividad
POST http://localhost:8080/actividades
Content-Type: application/json

{
    "nombre": "recoleccion de naranjas",
    "descripcion": "recolectamos naranjas", 
    "locacion": "arboleda del sector 1", 
    "diaDeLaSemana": 4, 
    "horaInicio": 23, 
    "horaFin": 24,
    "estado": 1,
    "cantidadMinima": 10,
    "edadMinima": 18, 
    "cod_sector": 1
}

### modificar an actividad
PUT http://localhost:8080/actividades/3
Content-Type: application/json

{
    "nombre": "recoleccion de naranjas radioactiva",
    "descripcion": "recolectamos naranjas radioactivas", 
    "locacion": "chernobyl sector 1", 
    "estado": 1
}






### get reclusos
GET http://localhost:8080/reclusos

### get reclusos
GET http://localhost:8080/reclusos/45655988

### POST a recluso
POST http://localhost:8080/reclusos
Content-Type: application/json

{
    "nombre": "Ia",
    "apellido": "Ka", 
    "dni": 450987, 
    "fecha_nac": "2004-06-10" 
}







### get all guardias
GET http://localhost:8080/guardias 

### get guardia
GET http://localhost:8080/guardias/45655988

### post guardia
POST http://localhost:8080/guardias 
Content-Type: application/json

{
    "nombre": "Ignacio",
    "apellido": "Chaparro", 
    "dni": 45655, 
    "fechaIniContrato": "2004-06-10" 
}

### finalizar contrato
PUT http://localhost:8080/guardias/finalizarContrato
Content-Type: application/json

{
    "cod_guardia": 1343
}






### get all de un sector en particular
GET http://localhost:8080/turnos/1

### get all turnos
GET http://localhost:8080/turnos

### crear turno
POST http://localhost:8080/turnos/  
Content-Type: application/json

{
    "cod_guardia": 6,
    "cod_sector": 1,
    "turno": "N"
}

### dar de baja un turno la diferencia con el de arriba es que este es put y el otro es post
PUT http://localhost:8080/turnos/
Content-Type: application/json

{
    "cod_guardia": 6,
    "cod_sector": 1,
    "turno": "N"
}





### get actividades ilegales
GET http://localhost:8080/actividadesIlegales

### get reclusos
GET http://localhost:8080/actividadesIlegales/3

### POST an actividad
POST http://localhost:8080/actividadesIlegales
Content-Type: application/json

{
    "nombre": "recoleccion de banans",
    "descripcion": "recolectamos naranjas", 
    "locacion": "arboleda del sector 1", 
    "diaDeLaSemana": 4, 
    "horaInicio": 23, 
    "horaFin": 24,
    "estado": 1,
    "cantidad_maxima": 10
}

### modificar an actividad
PUT http://localhost:8080/actividadesIlegales/9
Content-Type: application/json

{
    "nombre": "recoleccion de naranjas radioactiva",
    "descripcion": "recolectamos naranjas radioactivas", 
    "locacion": "chernobyl sector 1", 
    "estado": 1
}

### inscribir a act ilegal :cod_act_ilegal&:cod_recluso
POST http://localhost:8080/actividadesIlegales/inscripcion/9&28





### get all
GET http://localhost:8080/condenas

### agregar sentencias a sector, es importante que los campos tengan nombres diferentes
POST http://localhost:8080/condenas
Content-Type: application/json

{
    "cod_recluso": 42,
    "cod_sentencias": [1,4,5]
}

### finalizar condenas
PUT http://localhost:8080/condenas/finalizarCondenas






### get administradores
GET http://localhost:8080/administradores

### get administrador
GET http://localhost:8080/administradores/1


### POST a recluso
POST http://localhost:8080/administradores/logIn
Content-Type: application/json

{
    "cod_administrador": 11,
    "contrasenia": "muajaj"
}




### get talleres
GET http://localhost:8080/talleres

### get actividad
GET http://localhost:8080/talleres/5

### POST an actividad
POST http://localhost:8080/talleres
Content-Type: application/json

{
    "nombre": "re",
    "descripcion": "recolectamos naranjas", 
    "locacion": "arboleda del sector 1", 
    "diaDeLaSemana": 4, 
    "horaInicio": 23, 
    "horaFin": 24,
    "estado": 1
}

### inscripcion :cod_taller&:cod_recluso
POST http://localhost:8080/talleres/inscripcion/1&12

### modificar taller
PUT http://localhost:8080/talleres/5
Content-Type: application/json

{
    "nombre": "recoleccion de kiwis radioactivos",
    "descripcion": "recolectamos kiwis radioactivos", 
    "locacion": "arboleda del sector 1", 
    "diaDeLaSemana": 4, 
    "horaInicio": 23, 
    "horaFin": 24,
    "estado": 0
}







### get all sentencias
GET http://localhost:8080/sentencias



























