### get all
GET http://localhost:8080/guardias

### POST a guardia
# @name createGuardia
POST http://localhost:8080/guardias
Content-Type: application/json

{
  "nombre": "nachi",
  "apellido": "chap",
  "dni": 45690986,
  "fechaIniContrato": "10-10-24",
  "fechaFinContrato": null,
  "contrasenia": "12345"
}

### POST a guardia
# @name createGuardia
POST http://localhost:8080/guardias/logIn
Content-Type: application/json

{
  "cod_guardia": 1,
  "contrasenia": "pass"
}



### get one
GET http://localhost:8080/guardias


### update
PUT http://localhost:8080/guardias/10
Content-Type: application/json

{
  "nombre": "juan carlos bobo"
}


### borrar un character
DELETE http://localhost:8080/guardias/2

### creando recluso
POST http://localhost:8080/reclusos
Content-Type: application/json

{
  "nombre": "la",
  "apellido": "piedra",
  "dni": 74800490,
  "fecha_nac": "10-10-24"
}

### buscar act
GET http://localhost:8080/actividades




### crear actividad
POST http://localhost:8080/actividades
Content-Type: application/json

{
  "edad_minima": 1,
  "cod_sector_cod_sector": 1
}




### buscar rec
GET http://localhost:8080/reclusos

### crear actividad
POST http://localhost:8080/talleres
Content-Type: application/json

{
	"nombre": "mecanica",
	"descripcion": "mecanica",
	"locacion": "taller de mecanica",
	"diaDeLaSemana": 1,
	"horaInicio": 13,
	"horaFin": 14,
	"estado": 1
}

### inscripcion
POST http://localhost:8080/talleres/inscripcion/3&6

### buscar celdas
GET http://localhost:8080/celdas


### buscar celdas
GET http://localhost:8080/celdas/buscarPorSector/3



### inscripcion a taller
POST http://localhost:8080/talleres/inscripcion/3&4



### POST an actividad
POST http://localhost:8080/actividadesIlegales
Content-Type: application/json

{
	"nombre": "cosedo6",
	"descripcion": "tejemos",
	"locacion": "sala de tejidos",
	"diaDeLaSemana": 2,
	"horaInicio": "12",
	"horaFin": "13",
	"estado": 1,
	"cantidad_maxima": 4
}

### get all turnos
GET http://localhost:8080/turnos

### get
GET http://localhost:8080/actividadesIlegales

### post
POST http://localhost:8080/actividadesIlegales
Content-Type: application/json

{
 	"nombre": "jugar dota",
	"descripcion": "ser inhumano basicamente", 
	"duracion_anios": 1,
	"duracion_meses": 1, 
	"duracion_dias": 1,
	"orden_de_gravedad": 76
}

