### get all
GET http://localhost:8080/api/guardias

### post
# @name createActividad
POST http://localhost:8080/api/actividades
Content-Type: application/json

{
  "nombre": "recoleccion de mandarinas",
  "descripcion": "hay que recolectar mandarinas",
  "locacion": "pradera de mandarinas",
  "diaDeLaSemana": 5,
  "horaInicio": 14,
  "horaFin": 17
}

### ID
@elCod = {{createActividad.response.body.data.id}}

### get one
GET http://localhost:8080/api/actividades/{{elCod}}

### update
PUT http://localhost:8080/api/actividades/{{elCod}}
Content-Type: application/json

{
  "nombre": "recoleccion de mandarinas moradas",
  "descripcion": "hay que recolectar mandarinas moradas",
}


### borrar un character
DELETE http://localhost:8080/api/actividades/{{elCod}}

